/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;


public class AddNewGoodsForm extends ActionForm {
	
	private Integer cid;
	private String gname;
	private String pid;
	private String gbrief;
	private FormFile goodspic;
	private Integer gnum;
	private Double gprice;
	private Integer sub;

	public Integer getSub() {
		return sub;
	}

	public void setSub(Integer sub) {
		this.sub = sub;
	}

	public Integer getCid() {
		return cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}
	
	public String getGname() {
		return gname;
	}

	public void setGname(String gname) {
		this.gname = gname;
	}

	public String getPid() {
		return pid;
	}


	public void setPid(String pid) {
		this.pid = pid;
	}


	public String getGbrief() {
		return gbrief;
	}


	public void setGbrief(String gbrief) {
		this.gbrief = gbrief;
	}

	
	public Integer getGnum() {
		return gnum;
	}


	public void setGnum(Integer gnum) {
		this.gnum = gnum;
	}


	public Double getGprice() {
		return gprice;
	}

	public void setGprice(Double gprice) {
		this.gprice = gprice;
	}

	public FormFile getGoodspic() {
		return goodspic;
	}

	public void setGoodspic(FormFile goodspic) {
		this.goodspic = goodspic;
	}
}