/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.AddCCategoryForm;


public class AddCCategoryAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	
		AddCCategoryForm addCCategoryForm = (AddCCategoryForm) form;
		String addcname = addCCategoryForm.getAddCCategory();
		System.out.println(addcname);
		String pidString = request.getParameter("pno");
		int pid = Integer.parseInt(pidString);
		if (addcname.equals("")||addcname==null || pidString.equals("") || pidString==null) {
			return new ActionForward("/children.do?parentno="+pid);
		}else {
			PetDAO petDAO = new PetDAO();
			
			petDAO.addChildrenCategory(pid, addcname);
			return new ActionForward("/children.do?parentno="+pid);
		}
	}
}