/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.AddNewGoodsForm;

public class AddNewGoodsAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddNewGoodsForm addNewGoodsForm = (AddNewGoodsForm) form;
		
		String pid = addNewGoodsForm.getPid();
		String gname = addNewGoodsForm.getGname();
		double gprice = addNewGoodsForm.getGprice();
		int gnum = addNewGoodsForm.getGnum();
		String gbrief = addNewGoodsForm.getGbrief();
		System.out.println(pid);
		System.out.println(gname);
		System.out.println(gprice);
		System.out.println(gnum);
		System.out.println(gbrief);
		//int cid = Integer.parseInt(pid);
		int cid=7; //暂时设为7，待做了级联菜单后修改
		PetDAO petDAO = new PetDAO();
		//List list = petDAO.getCNameInOneCid(cid);
		petDAO.addNewGoods(cid,gname,gprice,gnum,gbrief);
		
		return new ActionForward("/showAllGoods.do");
	}
}