/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;




import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;


import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.AddNewGoodsForm;

public class AddNewGoodsAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddNewGoodsForm addNewGoodsForm = (AddNewGoodsForm) form;

		String gname = addNewGoodsForm.getGname();
		double gprice = addNewGoodsForm.getGprice();
		int gnum = addNewGoodsForm.getGnum();
		String gbrief = addNewGoodsForm.getGbrief();
		int cid = addNewGoodsForm.getSub();
		
	
		PetDAO petDAO = new PetDAO();
		int gid = petDAO.addNewGoods(cid,gname,gprice,gnum,gbrief);
		try {
			FormFile ff = addNewGoodsForm.getGoodspic();
			String text = ff.getContentType() ;
			if (!text.equals("image/jpeg")) {
				request.setAttribute("error", "Õº∆¨∏Ò Ω¥ÌŒÛ");
				return new ActionForward("/getPCategoryMap.do");
			}
			
			String path = this.getServlet().getServletContext().getRealPath("/");
			FileOutputStream fos = new FileOutputStream(path+"resource/"+gid+".jpg");
			fos.write(ff.getFileData());
			fos.close();
			
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return new ActionForward("/showAllGoods.do");
	}
}