/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.AddNewGoodsForm;

public class AddNewGoodsAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddNewGoodsForm addNewGoodsForm = (AddNewGoodsForm) form;
		
		
		String gname = addNewGoodsForm.getGname();
		double gprice = addNewGoodsForm.getGprice();
		int gnum = addNewGoodsForm.getGnum();
		String gbrief = addNewGoodsForm.getGbrief();
		int cid = addNewGoodsForm.getSub();

		PetDAO petDAO = new PetDAO();
		petDAO.addNewGoods(cid,gname,gprice,gnum,gbrief);
		return new ActionForward("/showAllGoods.do");
	}
}