/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.object.Order;
import cn.thepetshop.object.OrderInfo;

public class AdminGoodsAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String orderid=(String)request.getParameter("orderid");
		
		OrderInfo oi = new PetDAO().getOrderInfoByOrderId(Integer.parseInt(orderid));
		
		request.setAttribute("elist", oi.getGoodsList());
		request.setAttribute("orderid", orderid);
		
		return new ActionForward("AdminOrderGoodsListView");
	}
}