/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Random;

import javax.imageio.ImageIO;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class CheckNumAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		// 在内存中创建图象
		int width = 65, height = 20;
		BufferedImage image = new BufferedImage(width, height,
				BufferedImage.TYPE_INT_RGB);

		// 获取图形上下文
		Graphics g = image.getGraphics();

		// 设定背景色
		g.setColor(new Color(0xDCDCDC));
		g.fillRect(0, 0, width, height);

		// 画边框
		g.setColor(Color.black);
		g.drawRect(0, 0, width - 1, height - 1);

		// 随机产生的认证码(5位数字)
		String rand = "" + (Math.random() * 100000);
		rand = rand.substring(0, rand.indexOf("."));
		switch (rand.length()) {
		case 1:
			rand = "0000" + rand;
			break;
		case 2:
			rand = "000" + rand;
			break;
		case 3:
			rand = "00" + rand;
			break;
		case 4:
			rand = "0" + rand;
			break;
		default:
			rand = rand.substring(0, 5);
			break;
		}

		// 将认证码存入SESSION
		HttpSession session = request.getSession();
		session.setAttribute("rand", rand);

		// 将认证码显示到图象中
		g.setColor(Color.black);
		Integer tempNumber = new Integer(rand);
		String numberStr = tempNumber.toString();
		
		g.setFont(new Font("Atlantic Inline", Font.PLAIN, 18));
		String Str = numberStr.substring(0, 1);
		g.drawString(Str, 8, 17);

		Str = numberStr.substring(1, 2);
		g.drawString(Str, 20, 15);
		Str = numberStr.substring(2, 3);
		g.drawString(Str, 35, 18);
		
		Str = numberStr.substring(3, 4);
		g.drawString(Str, 45, 15);
	
		Str = numberStr.substring(4, 5);
		g.drawString(Str, 55, 15);
		
		// 图象生效
		g.dispose();

		// 输出图象到页面
		try {
			ImageIO.write(image, "JPEG", response.getOutputStream());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		// 在页面上调用 <img src="/yourPath/checkNum.jsp" />
		return null;
	}
}