/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Random;

import javax.imageio.ImageIO;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class CheckNumAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

BufferedImage bi = new BufferedImage(60,22,BufferedImage.TYPE_INT_RGB);
		
		response.setContentType("text/html");
		Graphics g = bi.getGraphics();
		Random rn = new Random();
		StringBuilder sbd = new StringBuilder();
		for(int i=0;i<4;i++){
			int s = rn.nextInt(10);
			sbd.append(""+s);
		}
		g.setColor(Color.white);

		g.setFont(new Font("楷体",Font.ITALIC,16));
		g.drawString(sbd.toString(), 6, 16);
		HttpSession sess = request.getSession();
		sess.setAttribute("rand", sbd.toString());
		
		//输出图片
		try {
			ImageIO.write(bi, "jpg", response.getOutputStream());
		} catch (IOException e) {
			e.printStackTrace();
		}
		// 在页面上调用 <img src="/yourPath/checkNum.jsp" />
		return null;
	}
}