/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;


public class ChildrenAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PetDAO pdao = new PetDAO();
		String cidstring = request.getParameter("parentno");
		if (cidstring==null || cidstring.equals("")) {
			return new ActionForward("AdminCCategoryView");
			
		}else {
			int cid = Integer.parseInt(cidstring);
			List clist = pdao.getChildrenCategory(cid);
			request.setAttribute("childrenList", clist);
			return new ActionForward("AdminCCategoryView");
		}
	
	}
}