/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.DelCCategoryForm;


public class DelCCategoryAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//DelCCategoryForm delCCategoryForm = (DelCCategoryForm) form;

		PetDAO petDAO = new PetDAO();
		
		String[] cjbno = request.getParameterValues("cjbnos");
		String pid = request.getParameter("parno");
		if (cjbno==null || cjbno.length<=0) {
			return new ActionForward("/children.do?parentno="+pid);
			
		}
		if(cjbno!=null && cjbno.length>0) {
			petDAO.deleteChildrenCategory(cjbno);
			return new ActionForward("/children.do?parentno="+pid);
		}else {
			return new ActionForward("/children.do?parentno="+pid);
		}
	
	}
}