/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;


public class DelOrderListAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PetDAO petDAO = new PetDAO();
		String[] orders = request.getParameterValues("orders");
		if (orders==null || orders.length<=0) {
			return new ActionForward("/showAllOrder.do");
		}
		if(orders!=null && orders.length>0) {
			petDAO.deleteOrderList(orders);
			return new ActionForward("/showAllOrder.do");
		}else {
			return new ActionForward("/showAllOrder.do");
		}
	}
}