/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.object.Cart;

public class GetCartAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String userid = (String)request.getSession().getAttribute("userid");
//		userid = "2";//¡Ÿ ±
		PetDAO pd = new PetDAO();
		Cart cart = pd.getShoppingCart(userid);
		request.setAttribute("cart", cart);
		return new ActionForward("MyCartView");
	}
}