/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.CategoryJavaBean;
import cn.thepetshop.dao.PetDAO;


public class GetCCategoryByParentAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		
		String cid = request.getParameter("cid");
		PetDAO petDAO = new PetDAO();
		String html = "";
		List list =petDAO.getChildrenCategory(Integer.parseInt(cid));
		
		try {
			PrintWriter out = response.getWriter();
			for (int i = 0; i < list.size(); i++) {
				html += "<option value='"+((CategoryJavaBean)list.get(i)).getCid()+"'>"+((CategoryJavaBean)list.get(i)).getCname()+"</option><br>";	
			}
			out.print(html);
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		return null;
	}
}