/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.GetAllGoods;
import cn.thepetshop.dao.PetDAO;


public class GetGoodsInfoAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String gid = request.getParameter("gid");
		PetDAO petDAO = new PetDAO();
		GetAllGoods list = petDAO.getGoodsListByGid(Integer.parseInt(gid));
		request.setAttribute("onegoodslist", list);
		return new ActionForward("AdminModGoodsView");
	}
}