/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

//import java.util.Iterator;
//import java.util.Set;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;


public class GetPCategoryMapAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		PetDAO petDAO = new PetDAO();
		Map map = petDAO.getPCategoryMap();
		//输出map中的信息，测试用
//		Set ks = map.keySet();
//		Iterator ite = ks.iterator();
//	    while(ite.hasNext()){
//	       Object key = ite.next();
//	       Object value = map.get(key);
//	       System.out.println(key + " = " + value);            
//	    }  
		request.setAttribute("pcategorymap", map);
		return new ActionForward("/admin/addnewGoods.jsp");
	}
}