/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.UserForm;

/**
 * 登录Action
 * 
 * @author Administrator
 * 
 */
public class LoginAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		UserForm userForm = (UserForm) form;
		
		String username = userForm.getUsername();
		String password = userForm.getPassword();
		System.out.println(userForm.isRemember());

		PetDAO petdao = new PetDAO();
		String userid = petdao.login(username, password);

		if (userid == null) {
			return new ActionForward("/index.jsp");
		}
		
		if (userForm.isRemember()) {
			int savetime = 3600;// 有效时间为3600秒
			System.out.println("logining.......");
			Cookie cid = new Cookie("username", username);
			Cookie cpass = new Cookie("password", password);
			cid.setMaxAge(savetime);
			cpass.setMaxAge(savetime);
			response.addCookie(cid);
			response.addCookie(cpass);
		}
		
		return new ActionForward("/myaccount/default.jsp", true);

	}
}