/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import cn.thepetshop.dao.PetDAO;


public class ModAdminPassAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//ModAdminPassForm modAdminPassForm = (ModAdminPassForm) form;
		String oldPass = request.getParameter("oldPass");
		String newPass = request.getParameter("newPass");
		PetDAO petDAO = new PetDAO();
		String msg =petDAO.updateAdministratorPass(oldPass, newPass);
		request.setAttribute("msg", msg);
		return new ActionForward("/modpass.jsp");
	}
}