/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.ModGoodsInfoForm;


public class ModGoodsInfoAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModGoodsInfoForm modGoodsInfoForm = (ModGoodsInfoForm) form;
		
		double gprice = modGoodsInfoForm.getGprice();
		int gnum = modGoodsInfoForm.getGnum();
		int gid = modGoodsInfoForm.getGid();
		String gname = modGoodsInfoForm.getGname();
		String gbrief = modGoodsInfoForm.getGbrief();
		
		PetDAO petDAO = new PetDAO();
		petDAO.modGoodsInfo(gid,gname,gnum,gprice,gbrief);
		return new ActionForward("/showAllGoods.do");
	}
}