/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.OrderForm;
import cn.thepetshop.object.OrderInfo;

public class SubmitOrderAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		OrderForm of = (OrderForm)form;
		PetDAO pd = new PetDAO();
		Object obj = request.getSession().getAttribute("userid");
		String userid = (String) obj;
		userid = "2";//临时用户ID
//		System.out.println("付款方式"+of.getPay());
		OrderInfo oi = pd.createOrder(userid,of.getReceiver(),of.getAddress(),of.getPhone(),of.getPay());
		request.setAttribute("orderedGoodsList", oi.getGoodsList());
		request.setAttribute("orderMoney", oi.getSumMoney());
//		System.out.println("订单提交 submit order");
		return null;//暂时为null。转到结算页面
	}
}