/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;


public class UpdateChildrenAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String pnoString = request.getParameter("cno");
		String newname = request.getParameter("text");
		int pno = Integer.parseInt(pnoString);

		if ( newname==null ||newname.equals("")) {

			try {
				PrintWriter pw = response.getWriter();
				pw.print(newname);
			} catch (IOException e) {
				e.printStackTrace();
			}
			return null;
			
		}else {
			PetDAO petDAO = new PetDAO();
			String new_name = petDAO.modChildrenCategory(pno,newname);
			try {
				PrintWriter pw = response.getWriter();
				pw.print(new_name);
			} catch (IOException e) {
				e.printStackTrace();
			}
			return null;
		}
	
	}
}