/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.UserForm;


public class UpdateUserPassAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		UserForm userForm = (UserForm)form;
		
		String username = userForm.getUsername();
		String password = userForm.getPassword();
		HttpSession session = request.getSession();
		String userid = (String)session.getAttribute("userid");
		PetDAO petdao = new PetDAO();
		boolean b = petdao.updateUserPass(userid, password);
		if(b){
		return new ActionForward("/usermsg.jsp");
		}
		else{
			return new ActionForward("/index.jsp");
		}
	}
}