/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.UserForm;


public class UpdateUserPassAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		UserForm userForm = (UserForm)form;
		
		HttpSession session = request.getSession();
		String userid = (String)session.getAttribute("userid");
		String oldpass = request.getParameter("oldpass");
		String newpass = request.getParameter("newpass");
		
		PetDAO petdao = new PetDAO();
		boolean b = petdao.updateUserPass(userid, oldpass,newpass);
		if(b){
			//System.out.println("ÐÞ¸Ä³É¹¦");
		return new ActionForward("/getUserMsg.do");	

		}
		else{
			return new ActionForward("/jsp/updatepass.jsp");
		}
	}
}