/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.thepetshop.dao.PetDAO;
import cn.thepetshop.form.UpdateChildrenForm;


public class UpdateChildrenAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UpdateChildrenForm updateChildrenForm = (UpdateChildrenForm) form;

		String cnoString = updateChildrenForm.getCno();
		String pnoString = updateChildrenForm.getPno();
		String newname = updateChildrenForm.getNewname();
		int pno = Integer.parseInt(pnoString);

		if ( newname==null ||newname.equals("")) {

			return new ActionForward("/children.do?parentno="+cnoString);
			
		}else {
			PetDAO petDAO = new PetDAO();
			petDAO.modChildrenCategory(pno,newname);
			return new ActionForward("/children.do?parentno="+cnoString);
		}
	
	}
}