/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import org.apache.struts.action.ActionForm;


public class AddCCategoryForm extends ActionForm {

	private String addCCategory;

	
	public String getAddCCategory() {
		return addCCategory;
	}

	
	public void setAddCCategory(String addCCategory) {
		this.addCCategory = addCCategory;
	}
}