/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import org.apache.struts.action.ActionForm;


public class AddPCategoryForm extends ActionForm {

	private String addCategory;

	
	public String getAddCategory() {
		return addCategory;
	}

	
	public void setAddCategory(String addCategory) {
		this.addCategory = addCategory;
	}
}