/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import org.apache.struts.action.ActionForm;


public class DelCCategoryForm extends ActionForm {
	
	private String cjbnos;

	private String parno;

	
	public String getCjbnos() {
		return cjbnos;
	}

	
	public void setCjbnos(String cjbnos) {
		this.cjbnos = cjbnos;
	}

	
	public String getParno() {
		return parno;
	}

	
	public void setParno(String parno) {
		this.parno = parno;
	}
}