/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-30-2011
 * 
 * XDoclet definition:
 * @struts.form name="modAdminPassForm"
 */
public class ModAdminPassForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** oldPass property */
	private String oldPass;

	/** newPass property */
	private String newPass;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the oldPass.
	 * @return String
	 */
	public String getOldPass() {
		return oldPass;
	}

	/** 
	 * Set the oldPass.
	 * @param oldPass The oldPass to set
	 */
	public void setOldPass(String oldPass) {
		this.oldPass = oldPass;
	}

	/** 
	 * Returns the newPass.
	 * @return String
	 */
	public String getNewPass() {
		return newPass;
	}

	/** 
	 * Set the newPass.
	 * @param newPass The newPass to set
	 */
	public void setNewPass(String newPass) {
		this.newPass = newPass;
	}
}