/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2011
 * 
 * XDoclet definition:
 * @struts.form name="modAdminPassForm"
 */
public class ModAdminPassForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** newPass1 property */
	private String newPass1;

	/** newPass2 property */
	private String newPass2;

	/** oldPass property */
	private String oldPass;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the newPass1.
	 * @return String
	 */
	public String getNewPass1() {
		return newPass1;
	}

	/** 
	 * Set the newPass1.
	 * @param newPass1 The newPass1 to set
	 */
	public void setNewPass1(String newPass1) {
		this.newPass1 = newPass1;
	}

	/** 
	 * Returns the newPass2.
	 * @return String
	 */
	public String getNewPass2() {
		return newPass2;
	}

	/** 
	 * Set the newPass2.
	 * @param newPass2 The newPass2 to set
	 */
	public void setNewPass2(String newPass2) {
		this.newPass2 = newPass2;
	}

	/** 
	 * Returns the oldPass.
	 * @return String
	 */
	public String getOldPass() {
		return oldPass;
	}

	/** 
	 * Set the oldPass.
	 * @param oldPass The oldPass to set
	 */
	public void setOldPass(String oldPass) {
		this.oldPass = oldPass;
	}
}