/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import org.apache.struts.action.ActionForm;


public class ModGoodsInfoForm extends ActionForm {
	
	private String gname;
	private String gbrief;
	private Integer gnum;
	private Double gprice;
	private Integer gid;

	public Integer getGid() {
		return gid;
	}


	public void setGid(Integer gid) {
		this.gid = gid;
	}


	public String getGname() {
		return gname;
	}


	public void setGname(String gname) {
		this.gname = gname;
	}

	
	public String getGbrief() {
		return gbrief;
	}

	
	public void setGbrief(String gbrief) {
		this.gbrief = gbrief;
	}


	public Integer getGnum() {
		return gnum;
	}

	
	public void setGnum(Integer gnum) {
		this.gnum = gnum;
	}


	public Double getGprice() {
		return gprice;
	}


	public void setGprice(Double gprice) {
		this.gprice = gprice;
	}
}