/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.thepetshop.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;


public class ModPCategoryForm extends ActionForm {

	private String cjbnos;

	private String newCategory;

	public String getCjbnos() {
		return cjbnos;
	}

	public void setCjbnos(String cjbnos) {
		this.cjbnos = cjbnos;
	}

	
	public String getNewCategory() {
		return newCategory;
	}

	
	public void setNewCategory(String newCategory) {
		this.newCategory = newCategory;
	}
}