/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.java.action;

import javax.jms.Session;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.upload.FormFile;

import com.java.dao.BookDao;
import com.java.dao.ManageCover;
import com.java.form.BookForm;

public class AddBookAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BookForm bookForm = (BookForm)form;
		
		FormFile ff = bookForm.getFile();
		int id = Integer.parseInt(bookForm.getId());
		String name = bookForm.getName();
		String author = bookForm.getAuthor();
		String publisher = bookForm.getPublisher();
		String publish_date = bookForm.getPublishDate();
		String price = bookForm.getPrice();
		String brief = bookForm.getBrief();
		
		ActionMessages messages = new ActionMessages();
		
		ManageCover mi = new ManageCover();
		
		if (mi.saveCover(ff, id,this.getServlet().getServletConfig().getServletContext().getRealPath("/"))) {
			BookDao bd = new BookDao();
			if (bd.newBook(id, name, author, publisher, publish_date, price,
					brief)) {
				return new ActionForward("/listBook.do",true);
			}
		}
		messages.add("upload",new ActionMessage("error.upload"));
		
		this.saveErrors(request, messages);
		
		return new ActionForward("BookFormView");
	}
}