/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.java.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.java.dao.BookDao;
import com.java.form.UserForm;


public class LogonAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;
		BookDao bd = new BookDao();
		
		if(bd.checkUser(userForm.getUsername(),userForm.getPassword())){
			request.getSession().setAttribute("username", userForm.getUsername());
			return new ActionForward("AlreadyLogonView");
		}else{
			ActionMessages messages = new ActionMessages();
			messages.add("username", new ActionMessage("error.logon"));
			this.saveErrors(request, messages);
		}
		
		return new ActionForward("LogonView");
	}
}